# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52d9328ba654cbf882d4dfc0cb09a36df81864cd1d7835009f09d5d6570c78b0b7141ba3f5af67fe06a242294ac046a54d326b349ad7d95c0b8cc0b51cdddbbe

test:
  secret_key_base: 1b2c241e4728215618d7b9a60392690ecf833a6d98826cfbf8349fe12868085e4aefe9fa8916c4d2a0dfa57b2d7b5b5c6f7b5a80bdabf4f896a2413f923e6a3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
